env:
  global:
    - CC_TEST_REPORTED_ID = 099164a99c84a22956315ab2f6a6be4e6b63d4c6b3645849c7b6ba72214f70cd

language: python

python:
  - "3.7"

os:
  linux

before_install:
  - pip install poetry
  - pip install pytest

install:
  - make install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make lint
  - make test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
